version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: "no"
    container_name: uber
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uber
      - MYSQL_USER=brook
      - MYSQL_PASSWORD=brook
      - MYSQL_ROOT_HOST=%
    ports:
      - "3311:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - /Users/brook/mysql-uber-server:/var/lib/mysql
